"""The initial task list of SmartDoc_Master_Implementation_Tracker.xlsx.

IDs are stable: never renumber or reuse one. New tasks are added with
`tracker.py add`, not by editing this file after the workbook exists.
Audit findings (AUD-xx) are the 20 CURRENT KNOWN RISKS from the 2026-09-26
post-implementation audit (https://claude.ai/artifact/WKskiyexTDLAHe1BfjvWR1).
"""

PHASES = {
    0: "Baseline, tracker, checkpoints",
    1: "Editor integrity + content preservation",
    2: "AI fidelity + destructive-operation review",
    3: "DOCX / OOXML preservation",
    4: "Security + resource limits",
    5: "Performance + autosave + history",
    6: "Accounts + billing + entitlements",
    7: "PDF fidelity foundation",
    8: "PDF -> editable MVP",
    9: "PDF layout-preserving architecture",
    10: "Translation MVP",
    11: "FontResolver + multilingual rendering",
    12: "Format by Example hardening",
    13: "Document Health 2.0",
    14: "Review Changes / Repair",
    15: "Batch operations",
    16: "Accessibility + advanced document features",
    17: "Final testing",
    18: "Production release audit",
}

# Category -> the sheet that lists its tasks.
CATEGORY_SHEETS = {
    "CORE": "DOCUMENT_FIDELITY",
    "FIDELITY": "DOCUMENT_FIDELITY",
    "REVIEW": "DOCUMENT_FIDELITY",
    "DOCX": "DOCX_OOXML",
    "PDF": "PDF",
    "EDITOR": "EDITOR",
    "FORMATTING": "FORMATTING",
    "HEALTH": "FORMATTING",
    "AI": "AI",
    "SECURITY": "SECURITY",
    "ACCOUNT": "SECURITY",
    "PERFORMANCE": "PERFORMANCE",
    "TESTING": "TESTING",
    "PRODUCT": "PRODUCT_FEATURES",
    "TRANSLATION": "TRANSLATION",
    "FONT": "TRANSLATION",
    "P2E": "PDF_TO_EDITABLE",
    "BILLING": "BILLING_PLANS",
    "INFRA": "INFRA",
    "JOBS": "INFRA",
    "STORAGE": "INFRA",
    "OBSERVABILITY": "INFRA",
    "DOCS": "INFRA",
}

# (id, parent, phase, category, title, description, priority, owner, deps, risk, audit)
TASKS = [
    # -- Phase 0 ------------------------------------------------------------------------
    ("INFRA-001", "", 0, "INFRA", "Excel control centre", "SmartDoc_Master_Implementation_Tracker.xlsx with MASTER, dashboard formulas, category views, conditional formatting, validation; tools/tracker CLI to update it.", "P0", "tools/tracker", "", "Low", ""),
    ("INFRA-002", "", 0, "INFRA", "Continuation system", "docs/AI-CONTINUATION.md + docs/session-state.json kept current at every checkpoint.", "P0", "docs", "INFRA-001", "Low", ""),
    ("INFRA-003", "", 0, "INFRA", "Resume reminder", "Session scheduler job that resumes from docs/AI-CONTINUATION.md while idle.", "P1", "session", "", "Low", ""),
    ("TEST-001", "", 0, "TESTING", "Baseline: backend tests", "Full pytest run recorded (count, failures, duration, coverage).", "P0", "backend/tests", "", "Low", ""),
    ("TEST-002", "", 0, "TESTING", "Baseline: frontend tests, typecheck, lint, build", "Vitest, tsc --noEmit, eslint, next build.", "P0", "frontend", "", "Low", ""),
    ("TEST-003", "", 0, "TESTING", "Baseline: Playwright E2E", "npm run test:e2e against the throwaway stack.", "P0", "frontend/e2e", "", "Low", ""),
    ("TEST-004", "", 0, "TESTING", "Baseline: migrations and database", "alembic upgrade/check/downgrade/upgrade on scratch DB; offline Postgres SQL; Supabase migrations + advisors.", "P0", "backend/alembic", "", "Low", ""),
    ("SEC-001", "", 0, "SECURITY", "Baseline: dependency audit", "pip-audit on both locks; npm audit.", "P1", "backend, frontend", "", "Low", ""),
    ("INFRA-004", "", 0, "INFRA", "Baseline: Docker, worker, storage", "docker compose config; Dockerfiles; arq worker; storage providers inspected.", "P1", "docker, jobs, storage", "", "Low", ""),
    ("TEST-005", "", 0, "TESTING", "Baseline: fixture inventory", "Golden fixtures + the audit's Word-authored fixtures inventoried.", "P1", "backend/tests/fixtures", "", "Low", ""),
    ("DOCS-001", "", 0, "DOCS", "current-baseline.md", "docs/architecture/current-baseline.md with measured baseline.", "P0", "docs", "TEST-001,TEST-002,TEST-003,TEST-004", "Low", ""),
    # -- Phase 1 ------------------------------------------------------------------------
    ("CORE-001", "", 1, "CORE", "Nested block containers in the model", "TableCell.blocks, ListItem.blocks and Element.children (quotes) hold lists, code, images, quotes, nested tables; recursive, validated, backwards compatible.", "P0", "backend/models", "", "High", "AUD-01,AUD-19"),
    ("CORE-002", "CORE-001", 1, "CORE", "OpenAPI + generated types for nested blocks", "Regenerate openapi.json and frontend types; contract test green.", "P0", "backend/scripts, frontend/types", "CORE-001", "Medium", "AUD-01"),
    ("CORE-003", "CORE-001", 1, "CORE", "Nested blocks through the backend", "Engine styles, asset externalisation, health, compare, version descriptions, usage/storage size traverse nested blocks.", "P0", "backend/formatting, services", "CORE-001", "High", "AUD-01"),
    ("EDIT-001", "", 1, "EDITOR", "Map nested blocks inside table cells", "tiptapToDocument: lists, code, images, quotes, nested tables in cells saved (no silent discard).", "P0", "frontend/editor", "CORE-002", "High", "AUD-01"),
    ("EDIT-002", "", 1, "EDITOR", "Map blocks inside list items", "Code blocks, images, extra paragraphs inside list items saved.", "P0", "frontend/editor", "CORE-002", "High", "AUD-01"),
    ("EDIT-003", "", 1, "EDITOR", "Map blocks inside quotes", "Lists, code, images inside blockquotes saved.", "P0", "frontend/editor", "CORE-002", "High", "AUD-01"),
    ("EDIT-004", "", 1, "EDITOR", "Render nested blocks back into the editor", "documentToTiptap renders every nested block kind.", "P0", "frontend/editor", "EDIT-001,EDIT-002,EDIT-003", "High", "AUD-01"),
    ("EDIT-005", "", 1, "EDITOR", "Save guard: never drop a node silently", "Any node the mapping cannot represent blocks the save with an explicit, user-visible error.", "P0", "frontend/editor", "EDIT-004", "High", "AUD-01"),
    ("EDIT-006", "", 1, "EDITOR", "Pasted rich HTML survives save", "Paste from Word/web (lists in cells, lists in quotes, code in items, images in cells) persists after reload.", "P0", "frontend/editor", "EDIT-005", "High", "AUD-01"),
    ("EDIT-007", "", 1, "EDITOR", "Canonical mark order", "No spurious save on open when backend and editor order marks differently.", "P2", "frontend/editor", "", "Low", "AUD-16"),
    ("DOCX-001", "", 1, "DOCX", "DOCX export of nested blocks", "Lists, images, code, nested tables in cells; blocks in list items; quote children.", "P0", "backend/export", "CORE-003", "High", "AUD-01"),
    ("PDF-001", "", 1, "PDF", "PDF export of nested blocks", "Same content in the PDF exporter.", "P0", "backend/export", "CORE-003", "Medium", "AUD-01"),
    ("FID-001", "", 1, "FIDELITY", "Structured Document Fidelity Report", "fidelityReport items: element, feature, source state, new state, confidence, reason, class (policy classes).", "P0", "backend/models", "", "Medium", "AUD-03"),
    ("FID-002", "FID-001", 1, "FIDELITY", "Importer reports every detected change", "Hidden text, caps, underline variants, numbering formats/continuation, sections, header variants, content controls, custom properties, links dropped, crop/rotation, table geometry, bullets in cells, empty paragraphs, autolinks, SmartArt/charts.", "P0", "backend/parsers", "FID-001", "High", "AUD-03,AUD-04,AUD-06,AUD-07,AUD-08"),
    ("FID-003", "FID-001", 1, "FIDELITY", "Export fidelity report", "What an export changes or drops is reported the same way.", "P0", "backend/export", "FID-001", "Medium", "AUD-03,AUD-18"),
    ("FID-004", "FID-001", 1, "FIDELITY", "Content protection UI", "Report panel + badge: 'No content changes' only when proven; otherwise 'N items require review'.", "P0", "frontend/editor", "FID-002", "Medium", "AUD-03"),
    ("FID-005", "FID-001", 1, "FIDELITY", "Unsupported-feature policy classes", "NOT_DETECTED, DETECTED_PRESERVED, DETECTED_NOT_EDITABLE, LOSSY, UNSUPPORTED, BLOCKED on every report item.", "P0", "backend/models", "FID-001", "Low", "AUD-03"),
    ("CORE-004", "", 1, "CORE", "Machine-readable capability matrix", "DOCX/PDF/editor capabilities (import/edit/export/round_trip) as data; served by the API; drives badges, warnings, tests.", "P1", "backend/capabilities", "FID-005", "Low", "AUD-20"),
    ("TEST-010", "", 1, "TESTING", "Regression tests for nested structures", "Backend unit/API, Vitest mapping, Playwright paste + reload.", "P0", "tests", "EDIT-006,DOCX-001", "Medium", "AUD-01"),
    # -- Phase 2 ------------------------------------------------------------------------
    ("AI-001", "", 2, "AI", "Content fidelity comparator", "Order-, count-, token-, numeric-, punctuation- and structure-aware diff of source vs AI output.", "P0", "backend/ai", "", "High", "AUD-02"),
    ("AI-002", "AI-001", 2, "AI", "Protected facts: numbers, units, percentages, dates, identifiers", "5 mg never becomes 50 mg without explicit user action.", "P0", "backend/ai", "AI-001", "High", "AUD-02"),
    ("AI-003", "AI-001", 2, "AI", "Structure analysis uses the comparator", "A piece that fails falls back alone; reasons logged without content.", "P0", "backend/ai", "AI-001", "Medium", "AUD-02"),
    ("AI-004", "AI-001", 2, "AI", "Adversarial fidelity tests", "Sentence/word deletion, 'not' removal, number/unit/percent/date change, added/reordered/duplicated sentence, punctuation, heading changes.", "P0", "backend/tests", "AI-003", "Low", "AUD-02"),
    ("AI-005", "", 2, "AI", "Classify AI operations", "Formatting-only vs content-changing (insert/delete/move/replace).", "P0", "backend/ai", "", "Medium", "AUD-05"),
    ("AI-006", "AI-005", 2, "AI", "PLAN -> VALIDATE -> PREVIEW -> ACCEPT -> APPLY", "Content-changing operations are stored as proposals and never applied without acceptance.", "P0", "backend/services", "AI-005,REV-001", "High", "AUD-05"),
    ("AI-007", "AI-006", 2, "AI", "Proposal review UI", "Preview, accept, reject AI proposals in the editor.", "P0", "frontend/editor", "AI-006", "Medium", "AUD-05"),
    ("AI-008", "", 2, "AI", "Per-document AI budget and deadline", "Token/time budget per document and job; no unbounded retries.", "P1", "backend/ai", "", "Medium", "AUD-02"),
    ("AI-009", "", 2, "AI", "Prompt-injection hardening review", "Document content never becomes instructions; output abuse checks.", "P1", "backend/ai", "", "Medium", ""),
    ("REV-001", "", 2, "REVIEW", "Change model", "{type, elementId, property, before, after, reason, source, confidence} with categories FORMAT/STRUCTURE/CONTENT/METADATA/PRESERVATION/TRANSLATION.", "P0", "backend/models", "", "Medium", "AUD-05"),
    ("CORE-005", "", 2, "CORE", "Document command model", "Commands with validate/preview/apply/undo for AI, translation, repair, batch.", "P1", "backend/services", "REV-001", "Medium", "AUD-05"),
    # -- Phase 3 ------------------------------------------------------------------------
    ("DOCX-010", "", 3, "DOCX", "Original package store", "Uploaded DOCX kept as an immutable source artifact (storage + DB reference, retention, deletion).", "P0", "backend/storage", "", "Medium", "AUD-03,AUD-06,AUD-18"),
    ("DOCX-011", "DOCX-010", 3, "DOCX", "Patch-writer export for imported documents", "Untouched OOXML parts preserved: styles, numbering, settings, theme, fontTable, webSettings, custom XML, glossary, docProps, commentsExtended, embeddings.", "P0", "backend/export", "DOCX-010", "High", "AUD-03,AUD-06,AUD-18"),
    ("DOCX-012", "", 3, "DOCX", "Metadata preserved and correct", "Core/app/custom properties kept; never 'python-docx'; created/modified correct; sensitivity properties kept where possible.", "P0", "backend/export", "DOCX-010", "Medium", "AUD-06,AUD-18"),
    ("DOCX-013", "", 3, "DOCX", "Character formatting", "Double underline and variants, double strike, caps, small caps, spacing, scale, position, language, RTL, theme font/colour, hidden text.", "P0", "backend/parsers, export, models", "DOCX-011", "High", "AUD-03"),
    ("DOCX-014", "", 3, "DOCX", "Paragraph formatting", "Right indent, keep-with-next, keep-lines, page-break-before, widow/orphan, outline level, tabs, borders, shading, direction, contextual spacing.", "P1", "backend/parsers, export, models", "DOCX-011", "Medium", "AUD-03"),
    ("DOCX-015", "", 3, "DOCX", "Sections as a first-class concept", "Breaks (next/continuous/even/odd), orientation, size, margins, columns, header/footer distance, first/even/odd headers, linked-to-previous, page-number restart.", "P0", "backend/models, parsers, export", "DOCX-011", "High", "AUD-03"),
    ("DOCX-016", "", 3, "DOCX", "Numbering engine", "Decimal/roman/alpha/bullets, custom prefixes/suffixes, start, restart, continuation, multilevel, numId/abstractNum/ilvl, indentation.", "P0", "backend/models, parsers, export", "DOCX-011", "High", "AUD-04"),
    ("DOCX-017", "", 3, "DOCX", "Table engine", "No forced header or Table Grid; widths, heights, margins, borders, shading, v-align, nested tables, repeated header rows, table styles.", "P0", "backend/models, parsers, export", "DOCX-011", "High", "AUD-08"),
    ("DOCX-018", "", 3, "DOCX", "Images", "Alt text exported; crop, rotation, anchor, wrap, position preserved; WEBP converted on export.", "P0", "backend/models, parsers, export", "DOCX-011", "Medium", "AUD-07"),
    ("DOCX-019", "", 3, "DOCX", "Drawings and text boxes preserved", "Anchored drawings, text boxes, shapes kept even when not editable.", "P1", "backend/export", "DOCX-011", "Medium", "AUD-03"),
    ("DOCX-020", "", 3, "DOCX", "Fields", "Code/result/relationship; header STYLEREF/DATE live; TOC kept; CITATION/BIBLIOGRAPHY sources preserved; no 'Invalid source specified.'", "P1", "backend/parsers, export", "DOCX-011", "Medium", "AUD-18"),
    ("DOCX-021", "", 3, "DOCX", "Comment threads", "Replies, resolved state, authors, ranges preserved (commentsExtended, people).", "P1", "backend/export", "DOCX-011", "Low", "AUD-06"),
    ("DOCX-022", "", 3, "DOCX", "Tracked changes preserved", "Not silently accepted; explicit choice.", "P1", "backend/parsers, export", "DOCX-011", "Medium", "AUD-03"),
    ("DOCX-023", "", 3, "DOCX", "Content controls preserved", "w:sdt of every kind kept with its properties.", "P1", "backend/parsers, export", "DOCX-011", "Medium", "AUD-06"),
    ("DOCX-024", "", 3, "DOCX", "Real footnotes and endnotes", "Notes stay notes on export.", "P1", "backend/export", "DOCX-011", "Medium", "AUD-03"),
    ("DOCX-025", "", 3, "DOCX", "Hidden text stays hidden", "Imported hidden text is kept hidden, shown only on request.", "P0", "backend/parsers, frontend", "DOCX-013", "Medium", "AUD-03"),
    ("DOCX-026", "", 3, "DOCX", "Hyperlink policy and no silent autolink", "Plain-text addresses not turned into links by default; file:/UNC reported.", "P0", "backend/parsers", "", "Low", "AUD-03,AUD-13"),
    ("FMT-004", "", 3, "FORMATTING", "Render-spec defaults respect the source", "Imported Word styles are not overridden by defaults (headings not forced bold).", "P0", "backend/formatting", "", "Medium", "AUD-03"),
    ("TEST-020", "", 3, "TESTING", "Word-authored fixtures in the repository", "20 synthetic Word-authored fixtures, scrubbed of identifying metadata.", "P0", "backend/tests/fixtures/word", "", "Low", "AUD-20"),
    ("TEST-021", "TEST-020", 3, "TESTING", "Expected-loss manifests in CI", "expected-loss.json per fixture; CI compares actual vs expected.", "P0", "backend/tests", "TEST-020", "Low", "AUD-20"),
    ("TEST-022", "TEST-020", 3, "TESTING", "True fidelity test", "SOURCE -> import -> format -> editor save -> export -> reimport -> compare SOURCE vs RESULT: content, formatting, metadata, structure separately.", "P0", "backend/tests", "TEST-021", "Medium", "AUD-20"),
    ("TEST-023", "", 3, "TESTING", "Independent validation", "OOXML schema validation, Word when available, docx2python; pdftotext/PyMuPDF for PDF.", "P1", "backend/tests", "TEST-022", "Low", "AUD-20"),
    # -- Phase 4 ------------------------------------------------------------------------
    ("SEC-010", "", 4, "SECURITY", "Malformed DOCX -> safe 4xx", "XML/zip/structure errors map to invalid_file; fuzz corpus shows no 500.", "P0", "backend/parsers", "", "Medium", "AUD-12"),
    ("SEC-011", "", 4, "SECURITY", "Malformed PDF -> safe 4xx", "Verified with a fuzz corpus.", "P0", "backend/parsers", "", "Low", "AUD-12"),
    ("SEC-012", "", 4, "SECURITY", "Image resource limits", "Compressed and decompressed size, pixel count, width, height, images per document, total bytes, format allowlist; rejected before rasterisation.", "P0", "backend/security", "", "High", "AUD-09"),
    ("SEC-013", "", 4, "SECURITY", "PDF bombs, huge XML, decompression limits", "Reviewed and tested limits.", "P1", "backend/security", "", "Medium", "AUD-09"),
    ("SEC-014", "", 4, "SECURITY", "Href policy", "Server-side scheme allowlist; javascript:/data:/vbscript:/file: never exported as active links.", "P0", "backend/models, export", "", "Medium", "AUD-13"),
    ("SEC-015", "", 4, "SECURITY", "Field instruction allowlist", "No DDE/INCLUDETEXT/INCLUDEPICTURE/external fields accepted from clients or exported.", "P0", "backend/export", "", "Medium", "AUD-13"),
    ("SEC-016", "", 4, "SECURITY", "External relationships policy", "No arbitrary external targets in exports.", "P1", "backend/export", "SEC-014", "Low", "AUD-13"),
    ("SEC-017", "", 4, "SECURITY", "Malicious SVG", "Verified refused everywhere.", "P1", "backend/security", "", "Low", ""),
    ("SEC-018", "", 4, "SECURITY", "Prompt injection / AI output abuse", "Tests with hostile documents; outputs validated.", "P1", "backend/ai", "AI-009", "Medium", ""),
    ("SEC-019", "", 4, "SECURITY", "Error envelope audit", "Every error {code, message, details, request_id}; no stack traces to users.", "P1", "backend/api", "", "Low", "AUD-12"),
    ("SEC-020", "", 4, "SECURITY", "CSP without 'unsafe-inline' scripts", "Nonce-based CSP for the Next.js app.", "P2", "frontend", "", "Medium", ""),
    ("TEST-030", "", 4, "TESTING", "Security regression suite", "Fuzz corpus, pixel bombs, href/field policy, IDOR, CSRF.", "P0", "backend/tests", "SEC-010,SEC-012,SEC-014,SEC-015", "Low", "AUD-09,AUD-12,AUD-13"),
    # -- Phase 5 ------------------------------------------------------------------------
    ("PERF-001", "", 5, "PERFORMANCE", "Linear DOCX table export", "500x8 table under a recorded threshold (baseline 321 s).", "P0", "backend/export", "", "High", "AUD-10"),
    ("PERF-002", "", 5, "PERFORMANCE", "Benchmarks recorded", "Baseline and current measurements in the PERFORMANCE sheet.", "P1", "tests/perf", "", "Low", "AUD-10"),
    ("PERF-003", "", 5, "PERFORMANCE", "Delta autosave", "Change-aware patches with a threshold strategy; whole document only when needed.", "P1", "frontend/editor, backend/api", "", "High", "AUD-16"),
    ("PERF-004", "", 5, "PERFORMANCE", "Bounded, compressed version history", "Editor history separate from persisted versions; compression/deltas; asset references.", "P1", "backend/services", "", "High", "AUD-16"),
    ("PERF-005", "", 5, "PERFORMANCE", "Editor at 5k-12k blocks", "Typing latency measured and improved.", "P2", "frontend/editor", "", "Medium", "AUD-16"),
    ("PERF-006", "", 5, "PERFORMANCE", "JSON without ASCII escaping", "Document JSON stored and sent as UTF-8.", "P2", "backend/db", "", "Low", ""),
    ("PERF-007", "", 5, "PERFORMANCE", "Safe size limits recorded", "User-facing maximum sizes, job timeouts, resource ceilings documented and enforced.", "P1", "backend/config", "", "Low", "AUD-09,AUD-10"),
    # -- Phase 6 ------------------------------------------------------------------------
    ("ACCT-001", "", 6, "ACCOUNT", "E-mail sender abstraction", "SMTP provider + development outbox; no secrets in logs.", "P0", "backend/services", "", "Medium", "AUD-14"),
    ("ACCT-002", "", 6, "ACCOUNT", "Password reset", "Single-use, expiring, hashed tokens; rate-limited; no account enumeration.", "P0", "backend/api, frontend", "ACCT-001", "High", "AUD-14"),
    ("ACCT-003", "", 6, "ACCOUNT", "E-mail verification", "Verification tokens and state.", "P0", "backend/api, frontend", "ACCT-001", "Medium", "AUD-14"),
    ("ACCT-004", "", 6, "ACCOUNT", "Password change", "Current password required; other sessions revoked.", "P0", "backend/api, frontend", "", "Medium", "AUD-14"),
    ("ACCT-005", "", 6, "ACCOUNT", "Account deletion", "Cascading policy: documents, versions, assets, exports, sessions, jobs, usage.", "P0", "backend/api, frontend", "", "High", "AUD-14"),
    ("ACCT-006", "", 6, "ACCOUNT", "Session revocation and cleanup", "Sign out everywhere; expired/revoked session sweep.", "P1", "backend/services", "", "Low", "AUD-14"),
    ("ACCT-007", "", 6, "ACCOUNT", "Suspicious login handling", "Lockout and notification strategy.", "P2", "backend/services", "ACCT-001", "Low", ""),
    ("PLAN-001", "", 6, "BILLING", "Usage units", "Documents, exports, PDF pages, OCR pages, translation characters, AI operations, storage, batch jobs.", "P0", "backend/billing", "", "Medium", "AUD-11"),
    ("PLAN-002", "", 6, "BILLING", "Configurable plan defaults", "Free/Pro/Business initial hypotheses as configuration, never hardcoded.", "P1", "backend/billing", "PLAN-001", "Low", ""),
    ("PLAN-003", "", 6, "BILLING", "Atomic entitlement checks", "Reservation/locking; concurrency test proves limits hold.", "P0", "backend/services", "PLAN-001", "High", "AUD-11"),
    ("PLAN-004", "", 6, "BILLING", "Stripe flows review", "Checkout, portal, upgrade, downgrade, cancel, renewal, failed payment, webhook idempotency.", "P1", "backend/billing", "", "Medium", ""),
    ("PLAN-005", "", 6, "BILLING", "Storage metering including history", "History and autosave growth counted.", "P1", "backend/services", "PLAN-001", "Medium", "AUD-11,AUD-16"),
    # -- Phase 7 ------------------------------------------------------------------------
    ("PDF-010", "", 7, "PDF", "Geometry-aware PDF parser", "Chars, fonts, sizes, colours, lines, rectangles, images, links, annotations, outlines, forms, metadata, rotation, page boxes.", "P0", "backend/parsers/pdf", "", "High", ""),
    ("PDF-011", "", 7, "PDF", "Page classifier", "TEXT / SCANNED / HYBRID per page with evidence.", "P0", "backend/parsers/pdf", "PDF-010", "Medium", ""),
    ("PDF-012", "", 7, "PDF", "PDF inspection report", "What the parser found, per page.", "P1", "backend/parsers/pdf", "PDF-010", "Low", ""),
    # -- Phase 8 ------------------------------------------------------------------------
    ("P2E-001", "", 8, "P2E", "Layout primitives where PDF needs them", "Page, block, bbox, rotation, confidence, provenance.", "P0", "backend/models", "PDF-010", "Medium", ""),
    ("P2E-002", "", 8, "P2E", "Structure reconstruction", "Reading order, lines, paragraphs, headings, lists, captions, header/footer bands, columns.", "P0", "backend/pdf", "P2E-001", "High", ""),
    ("P2E-003", "", 8, "P2E", "Images with position", "Extracted images kept with bbox.", "P1", "backend/pdf", "P2E-001", "Medium", ""),
    ("P2E-004", "", 8, "P2E", "Tables from PDF", "Ruling lines and alignment.", "P1", "backend/pdf", "P2E-002", "High", ""),
    ("P2E-005", "", 8, "P2E", "Confidence and conversion report", "Per element confidence; issues reported; never silent removal.", "P0", "backend/pdf", "P2E-002", "Medium", ""),
    ("P2E-006", "", 8, "P2E", "OCR provider abstraction", "Interface (text, confidence, bbox, page, language/script); implementation(s); OCR output untrusted.", "P1", "backend/ocr", "", "Medium", ""),
    ("P2E-007", "", 8, "P2E", "Imported-from-PDF version and UX", "Editable document vs layout-focused choice; confidence shown.", "P1", "frontend, backend", "P2E-005", "Medium", ""),
    ("P2E-008", "", 8, "P2E", "PDF fixtures and tests", "Text, scanned, hybrid, tables, columns, multilingual.", "P0", "backend/tests", "P2E-002", "Low", ""),
    # -- Phase 9 ------------------------------------------------------------------------
    ("P2E-020", "", 9, "P2E", "Layout-preserving architecture", "Frames/anchors model hooks and design doc.", "P2", "docs, backend/models", "P2E-001", "Medium", ""),
    ("PDF-020", "", 9, "PDF", "PDF page operations service", "Reorder, rotate, delete, duplicate, extract, split, merge as a separate service.", "P2", "backend/pdf", "", "Medium", ""),
    # -- Phase 10 -----------------------------------------------------------------------
    ("TRAN-001", "", 10, "TRANSLATION", "Segments and tag protocol", "Segments keep element/run ids, marks, placeholders; never one giant string.", "P0", "backend/translation", "", "High", ""),
    ("TRAN-002", "", 10, "TRANSLATION", "TranslationProvider abstraction", "AI provider implementation + deterministic test provider.", "P0", "backend/translation", "TRAN-001", "Medium", ""),
    ("TRAN-003", "", 10, "TRANSLATION", "Translation validation", "Tags, numbers, units, dates, percentages, identifiers, glossary terms.", "P0", "backend/translation", "TRAN-001", "High", ""),
    ("TRAN-004", "", 10, "TRANSLATION", "Glossary and terminology lock", "Source/target term, domain, locked, case-sensitive.", "P1", "backend/translation, db", "TRAN-001", "Medium", ""),
    ("TRAN-005", "", 10, "TRANSLATION", "Selection/paragraph/block translation proposals", "Preview; accept/reject; undo.", "P0", "backend, frontend", "TRAN-003,REV-001", "Medium", ""),
    ("TRAN-006", "", 10, "TRANSLATION", "Whole-document translated version", "Source kept; translated copy linked.", "P0", "backend, frontend", "TRAN-003", "Medium", ""),
    ("TRAN-007", "", 10, "TRANSLATION", "Language, script, direction metadata", "Auto-detect + manual override.", "P1", "backend/models", "", "Low", ""),
    ("TRAN-008", "", 10, "TRANSLATION", "Translation UX", "Toolbar/context Translate, target language, preview, accept/reject; 'AI-assisted translation - review required'.", "P0", "frontend", "TRAN-005", "Medium", ""),
    ("TRAN-009", "", 10, "TRANSLATION", "Translation metering", "Translation characters as a usage unit.", "P1", "backend/billing", "PLAN-001", "Low", ""),
    ("TRAN-010", "", 10, "TRANSLATION", "Translation tests", "Formatting preservation, validation, versions.", "P0", "backend/tests", "TRAN-006", "Low", ""),
    # -- Phase 11 -----------------------------------------------------------------------
    ("FONT-001", "", 11, "FONT", "Font catalogue with Unicode coverage", "fontTools cmap coverage per script, metrics, embeddability.", "P0", "backend/fonts", "", "Medium", "AUD-17"),
    ("FONT-002", "FONT-001", 11, "FONT", "FontResolver", "Script segmentation, coverage, fallback chain, embedding, RTL; deterministic first, AI suggestion validated.", "P0", "backend/fonts", "FONT-001", "Medium", "AUD-17"),
    ("FONT-003", "FONT-002", 11, "FONT", "Multilingual PDF rendering", "Shaping for Arabic/Hebrew/Devanagari, bidi, CJK fonts, emoji handled gracefully.", "P0", "backend/export", "FONT-002", "High", "AUD-17"),
    ("FONT-004", "FONT-002", 11, "FONT", "DOCX per-script fonts", "w:rFonts ascii/hAnsi/eastAsia/cs, w:lang, rtl/bidi.", "P1", "backend/export", "FONT-002", "Medium", "AUD-17"),
    ("FONT-005", "FONT-002", 11, "FONT", "Editor fallback stacks", "CSS stacks from the resolver.", "P2", "frontend", "FONT-002", "Low", ""),
    ("FONT-006", "FONT-003", 11, "FONT", "Multilingual tests", "Script matrix x editor/DOCX/PDF with pdftotext and rendering.", "P0", "backend/tests", "FONT-003", "Low", "AUD-17"),
    # -- Phase 12-16 --------------------------------------------------------------------
    ("FMT-001", "", 12, "FORMATTING", "Style extraction completeness", "Page setup, margins, fonts, headings, lists, tables, captions, headers/footers, spacing, numbering, colours.", "P1", "backend/formatting", "DOCX-016", "Medium", ""),
    ("FMT-002", "", 12, "FORMATTING", "Semantic mapping validated", "AI classifies/maps, engine applies; validation.", "P1", "backend/formatting", "", "Medium", ""),
    ("FMT-003", "", 12, "FORMATTING", "Before/after for Format by Example", "Preview before saving a template.", "P1", "frontend", "", "Low", ""),
    ("FMT-005", "", 12, "FORMATTING", "Rule value validation", "Instruction-path values validated before reaching CSS/export.", "P1", "backend/ai", "", "Low", ""),
    ("HLTH-001", "", 13, "HEALTH", "Health 2.0 checks", "Alt text, hidden text, mixed language, unsupported features, section inconsistency, broken lists, empty paragraphs, layout anomalies, duplicated formatting, broken links.", "P1", "backend/formatting", "FID-002", "Medium", ""),
    ("HLTH-002", "", 13, "HEALTH", "Deterministic fixes with preview", "Fix proposals through the change model.", "P1", "backend, frontend", "REV-001", "Medium", ""),
    ("HLTH-003", "", 13, "HEALTH", "AI explanations only", "AI explains issues; never scores.", "P2", "backend/ai", "", "Low", ""),
    ("REV-002", "", 14, "REVIEW", "Review Changes UI", "Categories FORMAT/STRUCTURE/CONTENT/METADATA/PRESERVATION/TRANSLATION.", "P0", "frontend", "REV-001", "Medium", "AUD-05"),
    ("REV-003", "REV-002", 14, "REVIEW", "Content changes need acceptance", "Enforced server-side.", "P0", "backend", "REV-001", "High", "AUD-05"),
    ("REV-004", "", 14, "REVIEW", "Repair", "Detected issue, proposed fix, preview, apply.", "P2", "backend, frontend", "REV-001", "Medium", ""),
    ("REV-005", "", 14, "REVIEW", "Clean copy", "Explicit: remove comments, accept tracked changes, remove hidden text, remove metadata, normalise formatting.", "P2", "backend, frontend", "DOCX-022", "Medium", ""),
    ("FEAT-001", "", 15, "PRODUCT", "Batch formatting", "One template/reference over many documents as jobs.", "P2", "backend/jobs", "", "Medium", ""),
    ("FEAT-002", "", 15, "PRODUCT", "Batch export", "Many documents to a zip.", "P2", "backend/jobs", "PERF-001", "Low", ""),
    ("FEAT-003", "", 15, "PRODUCT", "Batch translation", "After the translation MVP.", "P3", "backend/jobs", "TRAN-006", "Medium", ""),
    ("FEAT-010", "", 16, "PRODUCT", "Accessibility checker", "Heading hierarchy, alt text, link labels, table headers, reading order, language, contrast.", "P1", "backend/formatting", "HLTH-001", "Low", ""),
    ("FEAT-011", "", 16, "PRODUCT", "App accessibility fixes", "Zero serious axe violations on main pages and the editor.", "P1", "frontend", "", "Low", ""),
    # -- Infrastructure / observability / jobs / storage -----------------------------------
    ("JOB-001", "", 5, "JOBS", "Job safety", "idempotency_key, retry_count, timeout, cancellation, stuck detection, backoff, dead-letter.", "P1", "backend/jobs", "", "Medium", ""),
    ("STOR-001", "", 6, "STORAGE", "Storage retention and deletion", "Source files, exports, OCR artifacts: retention, deletion, access control, content types, size limits.", "P1", "backend/storage", "DOCX-010", "Medium", ""),
    ("OBS-001", "", 16, "OBSERVABILITY", "Metrics", "Latency, failure rate, job/AI/export metrics without content.", "P1", "backend", "", "Medium", "AUD-15"),
    ("OBS-002", "", 16, "OBSERVABILITY", "Operation and job IDs in logs", "Request, operation and job IDs everywhere.", "P1", "backend", "", "Low", "AUD-15"),
    ("OBS-003", "", 16, "OBSERVABILITY", "Operations data", "Failed jobs, processing failures, usage spikes, AI/export failures, storage, abuse - minimal admin API.", "P2", "backend", "OBS-001", "Low", "AUD-15"),
    ("INFRA-010", "", 17, "INFRA", "Deployment verified", "Docker images build and start; Postgres, Redis, storage, worker, frontend, backend.", "P1", "docker, CI", "", "High", "AUD-15"),
    ("INFRA-011", "", 17, "INFRA", "CI gates", "Backend, frontend, E2E, lint, typecheck, build, migrations, security audit, document fidelity tests.", "P0", ".github/workflows", "TEST-021", "Medium", "AUD-15,AUD-20"),
    ("TEST-040", "", 17, "TESTING", "Playwright workflow coverage", "The 24 workflows of the brief.", "P0", "frontend/e2e", "", "Medium", ""),
    ("TEST-041", "", 17, "TESTING", "Performance gates", "Regression thresholds relative to baseline.", "P1", "tests/perf", "PERF-002", "Low", ""),
    ("TEST-043", "", 17, "TESTING", "Browser matrix", "Chromium, Firefox, WebKit.", "P2", "frontend/e2e", "", "Low", ""),
    ("DOCS-010", "", 18, "DOCS", "final-production-readiness.md", "The 16-section final report.", "P0", "docs", "", "Low", ""),
    ("DOCS-011", "", 18, "DOCS", "Documentation tree", "docs/{architecture,document-model,docx,pdf,translation,ai,formatting,security,testing,deployment,billing,operations}.", "P1", "docs", "", "Low", ""),
]

AUDIT_FINDINGS = [
    ("AUD-01", "Editor save can discard nested blocks (lists, pictures, code, quotes inside cells/items)", "EDIT-001,EDIT-002,EDIT-003,EDIT-005,EDIT-006"),
    ("AUD-02", "AI fidelity check misses omissions, negation removal, number changes, inserted text", "AI-001,AI-002,AI-003,AI-004"),
    ("AUD-03", "Import/export silently changes hidden text, numbering, section headers, metadata, alt text, structure", "FID-002,DOCX-011,DOCX-013,DOCX-015,DOCX-025"),
    ("AUD-04", "List numbering changes ('Чл. 1.' -> '1.', '(a)' -> 'a.', start values)", "DOCX-016"),
    ("AUD-05", "AI instruction operations can delete/insert/move content without preview", "AI-005,AI-006,AI-007,REV-003"),
    ("AUD-06", "Content controls, metadata, comment threads, sensitivity information lost", "DOCX-012,DOCX-021,DOCX-023"),
    ("AUD-07", "Image fidelity gaps: alt text, crop, rotation, formats", "DOCX-018"),
    ("AUD-08", "Table export changes header state, borders, alignment, widths, geometry", "DOCX-017"),
    ("AUD-09", "Large images cause huge memory consumption", "SEC-012,SEC-013"),
    ("AUD-10", "Large tables have a performance problem", "PERF-001"),
    ("AUD-11", "Plan limits have a concurrency race", "PLAN-003"),
    ("AUD-12", "Malformed DOCX leads to HTTP 500", "SEC-010,SEC-019"),
    ("AUD-13", "Dangerous href/field instructions must be filtered", "SEC-014,SEC-015,SEC-016"),
    ("AUD-14", "Account essentials missing: reset, verification, change, deletion", "ACCT-002,ACCT-003,ACCT-004,ACCT-005"),
    ("AUD-15", "Operations/monitoring must be confirmed", "OBS-001,OBS-002,INFRA-010"),
    ("AUD-16", "Whole-document autosave must be optimised", "PERF-003,PERF-004"),
    ("AUD-17", "PDF multilingual rendering must be reliable", "FONT-003,FONT-006"),
    ("AUD-18", "Export metadata must be correct", "DOCX-012,DOCX-020"),
    ("AUD-19", "Canonical model must represent more than paragraphs + runs + simple tables", "CORE-001,DOCX-015,DOCX-016,DOCX-017"),
    ("AUD-20", "Tests can miss import-side data loss (model-relative comparison)", "TEST-020,TEST-021,TEST-022"),
]

RELEASE_GATES = [
    ("GATE-001", "No silent content loss", "TEST-022,EDIT-006,FID-002"),
    ("GATE-002", "No unauthorized document access", "TEST-030"),
    ("GATE-003", "AI cannot silently change content", "AI-004,AI-006"),
    ("GATE-004", "Plan limits atomic", "PLAN-003"),
    ("GATE-005", "Safe file uploads", "SEC-010,SEC-011,SEC-012"),
    ("GATE-006", "DOCX valid", "TEST-023"),
    ("GATE-007", "PDF valid", "TEST-023"),
    ("GATE-008", "Multilingual PDF readable", "FONT-006"),
    ("GATE-009", "PDF conversion has confidence/reporting", "P2E-005"),
    ("GATE-010", "Translation preserves formatting", "TRAN-010"),
    ("GATE-011", "No destructive translation overwrite", "TRAN-006"),
    ("GATE-012", "Critical E2E passes", "TEST-040"),
    ("GATE-013", "Migrations clean", "TEST-004"),
    ("GATE-014", "No high-severity security findings", "TEST-030,SEC-001"),
    ("GATE-015", "Monitoring exists", "OBS-001"),
]

# Section 61/62 of the brief: every product feature bucketed NOW / NEXT / LATER / ARCHITECTURE_ONLY.
# (feature, bucket, linked task IDs, notes)
PRODUCT_BACKLOG = [
    ("Document integrity", "NOW", "EDIT-001,EDIT-005,FID-002", "Brief 62: NOW #1"),
    ("Fidelity", "NOW", "DOCX-011,TEST-022", "Brief 62: NOW #2"),
    ("Security", "NOW", "SEC-010,SEC-012,SEC-014", "Brief 62: NOW #3"),
    ("Performance", "NOW", "PERF-001,PERF-003,PERF-004", "Brief 62: NOW #4"),
    ("PDF -> editable", "NOW", "P2E-002,P2E-005", "Brief 62: NOW #5"),
    ("Translation MVP", "NOW", "TRAN-001,TRAN-006", "Brief 62: NOW #6"),
    ("FontResolver", "NOW", "FONT-002,FONT-003", "Brief 62: NOW #7"),
    ("Review Changes", "NOW", "REV-001,REV-002", "Brief 62: NOW #8"),
    ("Document Health 2.0", "NOW", "HLTH-001,HLTH-002", "Brief 62: NOW #9"),
    ("Format by Example hardening", "NOW", "FMT-001,FMT-002,FMT-003", "Brief 62: NOW #10"),
    ("OCR", "NOW", "P2E-006", "Part of PDF -> editable (brief 43)"),
    ("Multilingual support", "NOW", "TRAN-007,FONT-003", "Part of translation + FontResolver"),
    ("RTL", "NOW", "FONT-003,FONT-004", "Part of FontResolver"),
    ("CJK", "NOW", "FONT-003", "Part of FontResolver"),
    ("Glossary", "NOW", "TRAN-004", "Part of translation MVP (brief 49)"),
    ("Terminology lock", "NOW", "TRAN-004", "Part of translation MVP (brief 49)"),
    ("Citation preservation", "NOW", "DOCX-020", "Preservation is fidelity work; a citation editor is LATER"),
    ("Bibliography preservation", "NOW", "DOCX-020", "Preservation is fidelity work"),
    ("Content controls", "NOW", "DOCX-023", "Preserve now; editing content controls NEXT"),
    ("Custom fields", "NOW", "DOCX-012,DOCX-020", "Preserve custom properties and fields now; an editor NEXT"),
    ("Document compare", "NEXT", "", "Brief 62: NEXT"),
    ("Version compare", "NEXT", "", ""),
    ("Batch formatting", "NEXT", "FEAT-001", "Brief 62: NEXT (batch processing)"),
    ("Batch export", "NEXT", "FEAT-002", "Brief 62: NEXT (batch processing)"),
    ("Batch translation", "NEXT", "FEAT-003", "After the translation MVP"),
    ("Repair", "NEXT", "REV-004", "Brief 62: NEXT"),
    ("Table repair", "NEXT", "REV-004", ""),
    ("List repair", "NEXT", "REV-004", ""),
    ("Accessibility checker", "NEXT", "FEAT-010", "Brief 62: NEXT (accessibility)"),
    ("Heading hierarchy checker", "NEXT", "FEAT-010", ""),
    ("Link checker", "NEXT", "HLTH-001", ""),
    ("Alt-text checker", "NEXT", "HLTH-001,FEAT-010", ""),
    ("Metadata editor", "NEXT", "", ""),
    ("Global style replacement", "NEXT", "", ""),
    ("Find/replace with formatting", "NEXT", "", ""),
    ("Clean copy", "NEXT", "REV-005", ""),
    ("Tracked change cleanup", "NEXT", "REV-005", ""),
    ("Template extraction", "NEXT", "FMT-001", ""),
    ("Document-to-template", "NEXT", "FMT-001", ""),
    ("Template matching", "NEXT", "", ""),
    ("Advanced template sharing", "NEXT", "", "Brief 62: NEXT"),
    ("Teams", "NEXT", "", "Brief 62: NEXT"),
    ("Translation memory", "NEXT", "", "Brief 62: NEXT"),
    ("PDF merge/split", "NEXT", "PDF-020", ""),
    ("Page reorder", "NEXT", "PDF-020", ""),
    ("Page rotate", "NEXT", "PDF-020", ""),
    ("Page delete", "NEXT", "PDF-020", ""),
    ("Page extract", "NEXT", "PDF-020", ""),
    ("Merge documents", "LATER", "", ""),
    ("Split documents", "LATER", "", ""),
    ("Watermark", "LATER", "", ""),
    ("Forms (advanced)", "LATER", "", "Brief 62: LATER"),
    ("SmartArt editing", "LATER", "", "Brief 62: LATER; SmartArt is preserved, not edited"),
    ("OLE", "LATER", "", "Brief 62: LATER; OLE objects preserved, not edited"),
    ("Full tracked-change editor", "LATER", "", "Brief 62: LATER"),
    ("Advanced citation manager", "LATER", "", "Brief 62: LATER"),
    ("Advanced drawing editor", "LATER", "", "Brief 62: LATER"),
    ("Layout-preserving PDF editing (frames/anchors)", "ARCHITECTURE_ONLY", "P2E-020", "Phase 9: architecture and hooks only"),
]

# Section 64: initial plan hypotheses (configurable; not final prices).
# (usage unit / feature, FREE, PRO, BUSINESS). "-" = not stated in the brief.
PLAN_DEFAULTS = [
    ("Documents / month", 5, 100, 1000),
    ("PDF conversion pages / month", 20, 500, 5000),
    ("OCR pages / month", 5, 100, 1000),
    ("Translation characters / month", 10000, 500000, 5000000),
    ("AI operations / month", 10, 300, 2000),
    ("Exports / month", 25, 500, "high"),
    ("Templates", "basic", "custom", "shared"),
    ("Formatting", "basic", "Format by Example", "-"),
    ("Advanced Document Health", "-", "yes", "-"),
    ("Version history", "-", "yes", "-"),
    ("Batch operations", "no", "reasonable limits", "yes"),
    ("Team workspace", "no", "-", "yes"),
    ("Priority processing", "-", "-", "yes"),
    ("Advanced controls", "-", "-", "yes"),
]

# Measured by the 2026-09-26 audit (audit/notes.md, out/perf_*.json).
# (id, scenario, metric, baseline, unit, source)
BENCHMARKS = [
    ("BENCH-001", "DOCX export: table 500x8 (4,000 cells)", "duration", 321, "s", "audit perf_table.py (400 cells 3.8 s; 1,600 cells 53.7 s; quadratic)"),
    ("BENCH-002", "PDF export: table 500x8", "duration", 1.4, "s", "audit perf_table.py (linear)"),
    ("BENCH-003", "Import: 300-page text DOCX (1,650 elements)", "duration", 0.328, "s", "audit perf_backend.py"),
    ("BENCH-004", "DOCX export: 300-page text document", "duration", 0.669, "s", "audit perf_backend.py"),
    ("BENCH-005", "PDF export: 300-page text document", "duration", 1.8, "s", "audit perf_backend.py"),
    ("BENCH-006", "PDF export: 39 KB DOCX holding a 12000x12000 PNG", "memory growth", 1382, "MB", "audit pixel_bomb.py (14000x14000 crashes the export)"),
    ("BENCH-007", "PDF export: 4 JPEG images 2400x1800", "memory growth", 180, "MB", "audit perf_backend.py (6.3 s)"),
    ("BENCH-008", "Editor: type 20 characters at 12,196 elements (1M-character paste)", "duration", 9.4, "s", "audit perf_browser.js (~470 ms per key)"),
    ("BENCH-009", "Editor: type 20 characters, 300-page document", "duration", 0.62, "s", "audit perf_browser.js"),
    ("BENCH-010", "Autosave request: 300-page document", "request size", 2.77, "MB", "audit perf_browser.js (whole elements list per save)"),
    ("BENCH-011", "Autosave request: 1M-character paste", "request size", 5.99, "MB", "audit perf_browser.js"),
    ("BENCH-012", "Stored history: one 300-page document, 50 steps", "storage", 140, "MB", "audit (2.8 MB per full copy; 7.2 MB when the JSON is ASCII-escaped)"),
    ("BENCH-013", "Paste: 2M characters (the cap)", "duration", 0.65, "s", "audit perf_backend.py (17.5k elements, 7.1 MB JSON)"),
]

STATUS_MEANINGS = [
    ("NOT_STARTED", "No work yet."),
    ("IN_PROGRESS", "Being implemented."),
    ("BLOCKED", "Cannot proceed; the reason is in Notes."),
    ("IMPLEMENTED", "Code written; not yet fully tested."),
    ("TESTING", "Tests being written or run."),
    ("VERIFIED", "Tests pass and evidence recorded; commit pending."),
    ("DONE", "Implemented + tested + verified; commit recorded."),
    ("FAILED", "Tests or verification failed; see Notes."),
    ("DEFERRED", "Consciously postponed; the reason is in Notes."),
    ("UNKNOWN", "State not established yet."),
]
