from abc import ABC, abstractmethod


class AssetNotFoundError(Exception):
    """Raised by StorageProvider.get() when nothing is stored under the key."""


class StorageProvider(ABC):
    """Where asset bytes live (doc §72). Keys are opaque, generated by
    services/asset_service.py; a provider never derives meaning from them."""

    @abstractmethod
    async def put(self, key: str, data: bytes, content_type: str) -> None: ...

    @abstractmethod
    async def get(self, key: str) -> bytes: ...

    @abstractmethod
    async def delete(self, key: str) -> None:
        """Idempotent: deleting a key that doesn't exist is not an error."""
