"""subscriptions cancel flag and stripe id indexes

Phase 14 (billing): whether a subscription ends at its period's end, and
indexes for the Stripe webhooks' lookups by customer / subscription id.

Revision ID: 85211092fe4c
Revises: ee14c191e210
Create Date: 2026-09-25 17:42:40.981764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85211092fe4c'
down_revision: Union[str, Sequence[str], None] = 'ee14c191e210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # sa.false(), not the generated text('0'): Postgres won't take an integer default for a boolean.
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'cancel_at_period_end')
    # ### end Alembic commands ###
