"""document revisions and version history

Revision ID: e68923f36278
Revises: e7958c683f5b
Create Date: 2026-09-24 10:39:08.081740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68923f36278'
down_revision: Union[str, Sequence[str], None] = 'e7958c683f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('kind', sa.String(length=20), server_default='change', nullable=False))
    op.add_column('documents', sa.Column('revision', sa.Integer(), server_default='1', nullable=False))
    op.add_column('documents', sa.Column('current_version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'current_version')
    op.drop_column('documents', 'revision')
    op.drop_column('document_versions', 'kind')
    # ### end Alembic commands ###
