"""index foreign key columns

Revision ID: e7958c683f5b
Revises: 4cbc55236361
Create Date: 2026-09-24 09:50:49.640292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7958c683f5b'
down_revision: Union[str, Sequence[str], None] = '4cbc55236361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_assets_document_id'), 'document_assets', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_created_by'), 'document_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_documents_created_by'), 'documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_documents_template_id'), 'documents', ['template_id'], unique=False)
    op.create_index(op.f('ix_export_jobs_result_asset_id'), 'export_jobs', ['result_asset_id'], unique=False)
    op.create_index(op.f('ix_formatting_profiles_created_by'), 'formatting_profiles', ['created_by'], unique=False)
    op.create_index(op.f('ix_processing_jobs_document_id'), 'processing_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_templates_created_by'), 'templates', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_created_by'), table_name='templates')
    op.drop_index(op.f('ix_processing_jobs_document_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_formatting_profiles_created_by'), table_name='formatting_profiles')
    op.drop_index(op.f('ix_export_jobs_result_asset_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_documents_template_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_by'), table_name='documents')
    op.drop_index(op.f('ix_document_versions_created_by'), table_name='document_versions')
    op.drop_index(op.f('ix_document_assets_document_id'), table_name='document_assets')
    # ### end Alembic commands ###
