"""documents formatted_at and workspace listing index

Revision ID: ee14c191e210
Revises: 5f5c3a367f6f
Create Date: 2026-09-25 17:07:13.284256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee14c191e210'
down_revision: Union[str, Sequence[str], None] = '5f5c3a367f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('formatted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_documents_workspace_id_updated_at', 'documents', ['workspace_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###
    # Documents already formatted -- a template applied, or instruction rules
    # (priority 2) -- count as formatted since their last change.
    if op.get_context().dialect.name == "postgresql":
        op.execute(
            "UPDATE documents SET formatted_at = updated_at "
            "WHERE data->>'templateId' IS NOT NULL OR data->'formattingRules' @> '[{\"priority\": 2}]'::jsonb"
        )
    else:
        op.execute("UPDATE documents SET formatted_at = updated_at WHERE json_extract(data, '$.templateId') IS NOT NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_workspace_id_updated_at', table_name='documents')
    op.drop_column('documents', 'formatted_at')
    # ### end Alembic commands ###
